### ISSUE TITLE
User sees Russian translation of Guides, now translation does not showq

### ISSUE THREAD

**Issue by baghdadbrian** [StoryMaker/storymaker#171]
Unfortunately, user could not recall what he was doing before this issue appeared, whether he:

A. deleted and redownloaded the packs

B. deleted and reinstalled the app and redownloaded

C. did nothing but checked again later and found the Russian translation no longer visible.

I have attached to logs from the user.
[bugreport_Russian-Nolongervisible.txt](https://github.com/StoryMaker/storymaker/files/437628/bugreport_Russian-Nolongervisible.txt)
[bugreport_Russian-Nolongervisible-2.txt](https://github.com/StoryMaker/storymaker/files/437629/bugreport_Russian-Nolongervisible-2.txt)

**Comment by n8fr8** [comment]
It is all showing up in English instead?

**Comment by n8fr8** [comment]
Is there phone set to Russian locale, or Ukranian or English?

**Comment by n8fr8** [comment]
It seems to me that when you go into guide, lessons, templates there are in Russian, but the titles are displaying in English. "Mobile Photo Basics" title and summary is in English, but if I open it, all of the content inside is Russian.

**Comment by n8fr8** [comment]
So this is where the catalog titles are specified, and it only seems to be in English, and these values are not linked into transifex in anyway:
https://github.com/StoryMaker/storypath/blob/4b28738ff1d089b549e7e81b7f72fb976a6051ef/lib/src/main/assets/available_index.json

@vitriolix is the catalog index localized in anyway? does the user pull down a new version of this file, potentially in their own language if available?

**Comment by baghdadbrian** [comment]
The user's device is set to English. I have asked user to check whether the device shows other languages as expected (I suggested Spanish, Farsi, and Arabic as these should be most complete)

**Comment by vitriolix** [comment]
@n8fr8 correct, currently we do not localize the table of content of the packs.  It's unfortunate but that is the case.

**Comment by n8fr8** [comment]
is that available_index.json file fetched/updated from the server, or always just loaded from the built-in asset? Regardless, it would be easy to replace the static displays strings in that file with variable that match to localized resource strings.

I know there is a long list of things that weren't done, but the idea that we spent all this effort creating localization of the app and all the content packs, but the titles themselves the user must use to choose which content to access are always in English is kind of nuts.

**Comment by vitriolix** [comment]
so I was mistaken, the TOC inside the packs is translated, the home screen titles is not at this point.  should treat that as a separate issue.  We'll need to have a script which splits out the string values from the content index into a flat json file we push to TX, then a script which generates localized index files we bundle in the app, and change the card loaders to read from the correctly localized files.  created a ticket for this:

https://github.com/StoryMaker/storymaker/issues/175
