### ISSUE TITLE
Dutch and Japanese are not available in the Language menu

### ISSUE THREAD

**Issue by baghdadbrian** [StoryMaker/storymaker#174]
The basic app and some content have been localized in Japanese and Dutch. According to @vitriolix these strings have been pulled into the app. However the user cannot access the languages as they are not included in the language menu.

**Comment by n8fr8** [comment]
What if they set their phone to dutch or japanese? By default, the app should use whatever language the phone is set to.

Otherwise, we need to add these new languages, and potentially others, to the supported language list so that people can also choose to switch to them.

**Comment by vitriolix** [comment]
Already done

**Comment by vitriolix** [comment]
fixed in 2.1.6
