### ISSUE TITLE
Why does it try to remove data from a GuardianProject app?

### ISSUE THREAD

**Issue by rugk** [StoryMaker/storymaker#178]
![guartdremo](https://cloud.githubusercontent.com/assets/11966684/20569906/f5c3079a-b1a1-11e6-94f8-bc91778d2fc9.png)

Why?

**Comment by n8fr8** [comment]
StoryMaker is a guardian project app. That is the old path for the StoryMaker v1 data. It should have been updated but maybe it was not.
