### ISSUE TITLE
Video is Null

### ISSUE THREAD

**Issue by baghdadbrian** [StoryMaker/storymaker#180]
I'm experiencing what looks like the same issue as at least one of the Ukrainians:

error #1231231 Video is Null.

This may be due to Android 7 issues, as Hamed is not sure the model and OS of the device used, but my device is an Android 7 device. bugreport attached.
[bugreport-NBD90W-2016-12-14-13-49-06.zip](https://github.com/StoryMaker/storymaker/files/653313/bugreport-NBD90W-2016-12-14-13-49-06.zip)

**Comment by baghdadbrian** [comment]
Still getting this error on the latest build when uploading to YouTube. This was a fresh install with the latest RC. So I had to authorize YouTube again. After it didn't work I disconnected and authorized again, still no dice

**Comment by n8fr8** [comment]
Hmm, it seems this is another bug that is before the YouTube auth process. This is the "video is null" bug that is related to sox on Addroid 6/7.
